### ISSUE TITLE
Wrong versioning in the filename for the latest tweakeroo file

### ISSUE THREAD

**Issue by DejonckheereWard** [maruohon/tweakeroo#151]
I downloaded the latest version of tweakeroo, only to find that it crashes running in 1.16.4. Upon further inspection i noticed that in the filename the version is correct, but on the curseforge website, it's listed for 1.16.5.
Not sure if the version is the cause of the crashing, but i reverted back to the older file that still works for me.
![image](https://user-images.githubusercontent.com/32327026/104859447-b88f6780-5925-11eb-9e18-befe05959662.png)

**Comment by maruohon** [comment]
Can you post the crash log? It is compiled for 1.16.4, but AFAIK all my clients mods should work in all versions between 1.16.2 - 1.16.5, as there were no vanilla changes between those versions that should affect them. I did test this in 1.16.4 in single player.

**Comment by DejonckheereWard** [comment]
Sure thing, i added it below.
Note that i am using multimc to run minecraft instead of the default launcher.

<details>
  <summary>Crash log</summary>
  
  ```java
MultiMC version: 0.6.11-1430


Minecraft folder is:
G:/MultiMC/instances/1.16.4/.minecraft


Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe


Java is version 1.8.0_271, using 64-bit architecture.


Main Class:
  net.fabricmc.loader.launch.knot.KnotClient

Native path:
  G:/MultiMC/instances/1.16.4/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  G:/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  G:/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  G:/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  G:/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  G:/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  G:/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  G:/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  G:/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  G:/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  G:/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  G:/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  G:/MultiMC/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  G:/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  G:/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  G:/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  G:/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  G:/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  G:/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  G:/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  G:/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  G:/MultiMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  G:/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  G:/MultiMC/libraries/com/mojang/authlib/2.1.28/authlib-2.1.28.jar
  G:/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  G:/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  G:/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  G:/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  G:/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  G:/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  G:/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  G:/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  G:/MultiMC/libraries/net/fabricmc/intermediary/1.16.4/intermediary-1.16.4.jar
  G:/MultiMC/libraries/net/fabricmc/tiny-mappings-parser/0.2.2.14/tiny-mappings-parser-0.2.2.14.jar
  G:/MultiMC/libraries/net/fabricmc/sponge-mixin/0.8.2+build.24/sponge-mixin-0.8.2+build.24.jar
  G:/MultiMC/libraries/net/fabricmc/tiny-remapper/0.3.0.70/tiny-remapper-0.3.0.70.jar
  G:/MultiMC/libraries/net/fabricmc/access-widener/1.0.0/access-widener-1.0.0.jar
  G:/MultiMC/libraries/net/fabricmc/fabric-loader-sat4j/2.3.5.4/fabric-loader-sat4j-2.3.5.4.jar
  G:/MultiMC/libraries/com/google/jimfs/jimfs/1.2-fabric/jimfs-1.2-fabric.jar
  G:/MultiMC/libraries/org/ow2/asm/asm/9.0/asm-9.0.jar
  G:/MultiMC/libraries/org/ow2/asm/asm-analysis/9.0/asm-analysis-9.0.jar
  G:/MultiMC/libraries/org/ow2/asm/asm-commons/9.0/asm-commons-9.0.jar
  G:/MultiMC/libraries/org/ow2/asm/asm-tree/9.0/asm-tree-9.0.jar
  G:/MultiMC/libraries/org/ow2/asm/asm-util/9.0/asm-util-9.0.jar
  G:/MultiMC/libraries/net/fabricmc/fabric-loader/0.11.1/fabric-loader-0.11.1.jar
  G:/MultiMC/libraries/com/mojang/minecraft/1.16.4/minecraft-1.16.4-client.jar

Native libraries:
  G:/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  G:/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  G:/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  G:/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  G:/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  G:/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  G:/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  G:/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [✔️] config-2-4.8.3
  [✔️] fabric-api-0.29.3+1.16
  [✔️] fabric-carpet-1.16.4-1.4.20+v201202
  [✔️] fabricmod_VoxelMap-1.10.14_for_1.16.4
  [✔️] malilib-fabric-1.16.4-0.10.0-dev.21+arne.2
  [📁] mamiyaotaru (folder)
  [✔️] minihud-fabric-1.16.4-0.19.0-dev.20201103.184029
  [✔️] modmenu-1.14.13+build.19
  [✔️] mousewheelie-1.6.2+mc1.16.4
  [✔️] optifabric-1.8.16
  [✔️] OptiFine_1.16.4_HD_U_G6
  [✔️] RoughlyEnoughItems-5.8.10
  [✔️] tweakeroo-fabric-1.16.4-0.10.0-dev.20201110.132827.jar
  [✔️] tweakeroo-fabric-1.16.4-0.10.0-dev.20210117.164212

Params:
  --username  --version MultiMC5 --gameDir G:/MultiMC/instances/1.16.4/.minecraft --assetsDir G:/MultiMC/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms256m, -Xmx4096m, -Duser.language=en]


Minecraft process ID: 19192


Using onesix launcher.

[01:56:17] [main/INFO]: Loading for game Minecraft 1.16.4
[01:56:17] [ForkJoinPool-1-worker-4/WARN]: Non-Fabric mod JAR at "G:\MultiMC\instances\1.16.4\.minecraft\mods\OptiFine_1.16.4_HD_U_G6.jar", ignoring
[01:56:17] [main/WARN]: Warnings were found! 
 - Conflicting versions found for fabric-lifecycle-events-v1: used 1.2.0+ffb68a873a, also found 1.2.0+74cc3b20a7
 - Conflicting versions found for fabric-key-binding-api-v1: used 1.0.1+730711c63a, also found 1.0.1+730711c6a7
 - Conflicting versions found for fabric-events-lifecycle-v0: used 0.2.0+16acbe5ba7, also found 0.2.0+6a2618f53a
[01:56:17] [main/INFO]: [FabricLoader] Loading 64 mods: fabric-renderer-api-v1@0.4.0+cbe9176f3a, fabric-keybindings-v0@0.2.0+6a2618f53a, roughlyenoughitems-api@5.8.10, fabricloader@0.11.1, fabric-structure-api-v1@1.1.3+cbe9176f3a, fabric-containers-v0@0.1.9+a03e98793a, fabric-dimensions-v1@2.0.1+9a6c75813a, fabric-object-builder-api-v1@1.9.2+6a2618f53a, java@8, fabric-game-rule-api-v1@1.0.5+cbe9176f3a, fabric-api-base@0.2.0+ab87788d3a, fabric-rendering-data-attachment-v1@0.1.4+6a2618f53a, mm@2.1, fabric-textures-v0@1.0.5+6a2618f53a, tweakeroo@0.10.0-dev.20210117.164212, fabric-rendering-fluids-v1@0.1.12+6a2618f53a, fabric-blockrenderlayer-v1@1.1.4+6a2618f53a, fabric-lifecycle-events-v1@1.2.0+ffb68a873a, fabric-renderer-registries-v1@2.2.0+6a2618f53a, minihud@0.19.0-dev.20201103.184029, fabric-loot-tables-v1@1.0.1+6a2618f53a, fabric@0.29.3+1.16, carpet@1.4.20, fabric-particles-v1@0.2.3+cbe9176f3a, fabric-networking-v0@0.3.1+2a4333d33a, fabric-networking-blockentity-v0@0.2.7+a03e98793a, minecraft@1.16.4, fabric-screen-handler-api-v1@1.1.0+6a2618f53a, roughlyenoughitems-default-plugin@5.8.10, modmenu@1.14.13+build.19, fabric-command-api-v1@1.0.9+6a2618f53a, cloth-basic-math@0.5.1, amecsapi@1.1.1+mc1.16-rc1, fabric-tool-attribute-api-v1@1.2.5+6a2618f53a, fabric-renderer-indigo@0.4.3+6a2618f53a, roughlyenoughitems-runtime@5.8.10, cloth-client-events-v0@1.4.5, fabric-crash-report-info-v1@0.1.2+b7f9825d3a, fabric-item-api-v1@1.2.0+6a2618f53a, fabric-events-interaction-v0@0.4.1+6a2618f53a, roughlyenoughitems@5.8.10, fabric-entity-events-v1@1.0.2+8004b36d3a, fabric-rendering-v0@1.1.1+6a2618f53a, fabric-key-binding-api-v1@1.0.1+730711c63a, fabric-rendering-v1@1.5.0+c26373133a, mousewheelie@1.6.2+mc1.16.4, cloth-config2@4.8.3, autoconfig1u@3.3.1, fabric-resource-loader-v0@0.4.1+0d4d7e343a, malilib@0.10.0-dev.21+arne.2, fabric-content-registries-v0@0.2.0+e77439c73a, fabric-tag-extensions-v0@1.1.0+e77439c73a, optifabric@1.8.16, fabric-biome-api-v1@3.1.0+2e23b97c3a, fabric-registry-sync-v0@0.7.3+be155ae23a, fabric-commands-v0@0.2.1+cbe9176f3a, fabric-mining-levels-v0@0.1.2+6a2618f53a, fabric-networking-api-v1@1.0.0+4358fbc63a, voxelmap@1.10.14, fabric-events-lifecycle-v0@0.2.0+16acbe5ba7, fabric-item-groups-v0@0.2.2+cbe9176f3a, fabric-models-v0@0.2.0+cbe9176f3a, fabric-object-builders-v0@0.7.1+6a2618f53a, tweed@3.0.0-beta.22
[01:56:17] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/G:/MultiMC/libraries/net/fabricmc/sponge-mixin/0.8.2+build.24/sponge-mixin-0.8.2+build.24.jar Service=Knot/Fabric Env=CLIENT
Found existing patched optifine jar, using that
[01:56:19] [main/WARN]: @Redirect conflict. Skipping carpet.mixins.json:WorldRenderer_creativeNoClipMixin->@Redirect::canSeeWorld(Lnet/minecraft/class_746;)Z with priority 1000, already redirected by mixins.tweakeroo.json:MixinWorldRenderer->@Redirect::overrideIsSpectator(Lnet/minecraft/class_746;)Z with priority 1001
[01:56:19] [main/WARN]: @Redirect conflict. Skipping carpet.mixins.json:WorldRenderer_creativeNoClipMixin->@Redirect::canSeeWorld(Lnet/minecraft/class_746;)Z with priority 1000, already redirected by mixins.tweakeroo.json:MixinWorldRenderer->@Redirect::overrideIsSpectator(Lnet/minecraft/class_746;)Z with priority 1001
[01:56:19] [main/WARN]: @Redirect conflict. Skipping carpet.mixins.json:WorldRenderer_creativeNoClipMixin->@Redirect::canSeeWorld(Lnet/minecraft/class_746;)Z with priority 1000, already redirected by mixins.tweakeroo.json:MixinWorldRenderer->@Redirect::overrideIsSpectator(Lnet/minecraft/class_746;)Z with priority 1001
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:228)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	... 8 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	... 10 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:287)
	at net.minecraft.class_128.method_559(class_128.java:101)
	at net.minecraft.class_128.<init>(class_128.java:54)
	at net.minecraft.class_128.method_24305(class_128.java:425)
	at net.minecraft.client.main.Main.main(Main.java:135)
	... 15 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector canSeeWorld(Lnet/minecraft/class_746;)Z in carpet.mixins.json:WorldRenderer_creativeNoClipMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap fabric-carpet-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 26 more
Exiting with -1
Process exited with code -1.

  ```
  
</details>
<details>
  <summary>Minecraft log</summary>
 
  ```
[01:56:17] [main/INFO]: Loading for game Minecraft 1.16.4
[01:56:17] [ForkJoinPool-1-worker-4/WARN]: Non-Fabric mod JAR at "G:\MultiMC\instances\1.16.4\.minecraft\mods\OptiFine_1.16.4_HD_U_G6.jar", ignoring
[01:56:17] [main/WARN]: Warnings were found! 
 - Conflicting versions found for fabric-lifecycle-events-v1: used 1.2.0+ffb68a873a, also found 1.2.0+74cc3b20a7
 - Conflicting versions found for fabric-key-binding-api-v1: used 1.0.1+730711c63a, also found 1.0.1+730711c6a7
 - Conflicting versions found for fabric-events-lifecycle-v0: used 0.2.0+16acbe5ba7, also found 0.2.0+6a2618f53a
[01:56:17] [main/INFO]: [FabricLoader] Loading 64 mods: fabric-renderer-api-v1@0.4.0+cbe9176f3a, fabric-keybindings-v0@0.2.0+6a2618f53a, roughlyenoughitems-api@5.8.10, fabricloader@0.11.1, fabric-structure-api-v1@1.1.3+cbe9176f3a, fabric-containers-v0@0.1.9+a03e98793a, fabric-dimensions-v1@2.0.1+9a6c75813a, fabric-object-builder-api-v1@1.9.2+6a2618f53a, java@8, fabric-game-rule-api-v1@1.0.5+cbe9176f3a, fabric-api-base@0.2.0+ab87788d3a, fabric-rendering-data-attachment-v1@0.1.4+6a2618f53a, mm@2.1, fabric-textures-v0@1.0.5+6a2618f53a, tweakeroo@0.10.0-dev.20210117.164212, fabric-rendering-fluids-v1@0.1.12+6a2618f53a, fabric-blockrenderlayer-v1@1.1.4+6a2618f53a, fabric-lifecycle-events-v1@1.2.0+ffb68a873a, fabric-renderer-registries-v1@2.2.0+6a2618f53a, minihud@0.19.0-dev.20201103.184029, fabric-loot-tables-v1@1.0.1+6a2618f53a, fabric@0.29.3+1.16, carpet@1.4.20, fabric-particles-v1@0.2.3+cbe9176f3a, fabric-networking-v0@0.3.1+2a4333d33a, fabric-networking-blockentity-v0@0.2.7+a03e98793a, minecraft@1.16.4, fabric-screen-handler-api-v1@1.1.0+6a2618f53a, roughlyenoughitems-default-plugin@5.8.10, modmenu@1.14.13+build.19, fabric-command-api-v1@1.0.9+6a2618f53a, cloth-basic-math@0.5.1, amecsapi@1.1.1+mc1.16-rc1, fabric-tool-attribute-api-v1@1.2.5+6a2618f53a, fabric-renderer-indigo@0.4.3+6a2618f53a, roughlyenoughitems-runtime@5.8.10, cloth-client-events-v0@1.4.5, fabric-crash-report-info-v1@0.1.2+b7f9825d3a, fabric-item-api-v1@1.2.0+6a2618f53a, fabric-events-interaction-v0@0.4.1+6a2618f53a, roughlyenoughitems@5.8.10, fabric-entity-events-v1@1.0.2+8004b36d3a, fabric-rendering-v0@1.1.1+6a2618f53a, fabric-key-binding-api-v1@1.0.1+730711c63a, fabric-rendering-v1@1.5.0+c26373133a, mousewheelie@1.6.2+mc1.16.4, cloth-config2@4.8.3, autoconfig1u@3.3.1, fabric-resource-loader-v0@0.4.1+0d4d7e343a, malilib@0.10.0-dev.21+arne.2, fabric-content-registries-v0@0.2.0+e77439c73a, fabric-tag-extensions-v0@1.1.0+e77439c73a, optifabric@1.8.16, fabric-biome-api-v1@3.1.0+2e23b97c3a, fabric-registry-sync-v0@0.7.3+be155ae23a, fabric-commands-v0@0.2.1+cbe9176f3a, fabric-mining-levels-v0@0.1.2+6a2618f53a, fabric-networking-api-v1@1.0.0+4358fbc63a, voxelmap@1.10.14, fabric-events-lifecycle-v0@0.2.0+16acbe5ba7, fabric-item-groups-v0@0.2.2+cbe9176f3a, fabric-models-v0@0.2.0+cbe9176f3a, fabric-object-builders-v0@0.7.1+6a2618f53a, tweed@3.0.0-beta.22
[01:56:17] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/G:/MultiMC/libraries/net/fabricmc/sponge-mixin/0.8.2+build.24/sponge-mixin-0.8.2+build.24.jar Service=Knot/Fabric Env=CLIENT
[01:56:19] [main/WARN]: @Redirect conflict. Skipping carpet.mixins.json:WorldRenderer_creativeNoClipMixin->@Redirect::canSeeWorld(Lnet/minecraft/class_746;)Z with priority 1000, already redirected by mixins.tweakeroo.json:MixinWorldRenderer->@Redirect::overrideIsSpectator(Lnet/minecraft/class_746;)Z with priority 1001
[01:56:19] [main/WARN]: @Redirect conflict. Skipping carpet.mixins.json:WorldRenderer_creativeNoClipMixin->@Redirect::canSeeWorld(Lnet/minecraft/class_746;)Z with priority 1000, already redirected by mixins.tweakeroo.json:MixinWorldRenderer->@Redirect::overrideIsSpectator(Lnet/minecraft/class_746;)Z with priority 1001
[01:56:19] [main/WARN]: @Redirect conflict. Skipping carpet.mixins.json:WorldRenderer_creativeNoClipMixin->@Redirect::canSeeWorld(Lnet/minecraft/class_746;)Z with priority 1000, already redirected by mixins.tweakeroo.json:MixinWorldRenderer->@Redirect::overrideIsSpectator(Lnet/minecraft/class_746;)Z with priority 1001

  ```
  
</details>

**Comment by maruohon** [comment]
Ah crap, the Free Camera fix now conflicts with Carpet mod :(

**Comment by maruohon** [comment]
The version numbers are correct, the mod is still compiled against 1.16.4, but works also in 1.16.5.
The crash with FabricCarpet should be fixed in the 2021-01-18 build.
