### ISSUE TITLE
Minecraft crash

### ISSUE THREAD

**Issue by Wikinger8** [maruohon/tweakeroo#236]
Minecraft crash if you enable or disable the disableSlimeBlockSlowdown feature.

**Comment by DragonEggBedrockBreaking** [comment]
Please provide a crash report.

**Comment by Wikinger8** [comment]
The game crashed whilst mouseclicked event handler
Error: java.lang.IllegalAccessError: Update to non-static final field net.minecraft.class_4970.field_23163 attempted from a different method (setFriction) than the initializer method <init> 
Exit-Code: -1

**Comment by DragonEggBedrockBreaking** [comment]
That isnt the full crash report. Provide the latest file in `.minecraft/crash-reports/`

**Comment by Wikinger8** [comment]
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 03.06.21, 16:25
Description: mouseClicked event handler

java.lang.IllegalAccessError: Update to non-static final field net.minecraft.class_4970.field_23163 attempted from a different method (setFriction) than the initializer method <init> 
	at net.minecraft.class_4970.setFriction(class_4970.java)
	at fi.dy.masa.tweakeroo.config.Callbacks$FeatureCallbackSlime.onValueChanged(Callbacks.java:193)
	at fi.dy.masa.tweakeroo.config.Callbacks$FeatureCallbackSlime.onValueChanged(Callbacks.java:171)
	at fi.dy.masa.malilib.config.options.ConfigBase.onValueChanged(ConfigBase.java:75)
	at fi.dy.masa.malilib.config.options.ConfigBoolean.setBooleanValue(ConfigBoolean.java:47)
	at fi.dy.masa.malilib.config.options.ConfigTypeWrapper.setBooleanValue(ConfigTypeWrapper.java:307)
	at fi.dy.masa.malilib.config.IConfigBoolean.toggleBooleanValue(IConfigBoolean.java:13)
	at fi.dy.masa.malilib.gui.button.ConfigButtonBoolean.onMouseClickedImpl(ConfigButtonBoolean.java:21)
	at fi.dy.masa.malilib.gui.widgets.WidgetBase.onMouseClicked(WidgetBase.java:92)
	at fi.dy.masa.malilib.gui.widgets.WidgetContainer.onMouseClicked(WidgetContainer.java:64)
	at fi.dy.masa.malilib.gui.widgets.WidgetListBase.onMouseClicked(WidgetListBase.java:109)
	at fi.dy.masa.malilib.gui.widgets.WidgetListConfigOptionsBase.onMouseClicked(WidgetListConfigOptionsBase.java:47)
	at fi.dy.masa.malilib.gui.GuiListBase.onMouseClicked(GuiListBase.java:97)
	at fi.dy.masa.malilib.gui.GuiConfigsBase.onMouseClicked(GuiConfigsBase.java:192)
	at fi.dy.masa.malilib.gui.GuiBase.method_25402(GuiBase.java:196)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:490)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:101)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:165)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1139)
	at net.minecraft.class_310.method_1514(class_310.java:730)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_4970.setFriction(class_4970.java)
	at fi.dy.masa.tweakeroo.config.Callbacks$FeatureCallbackSlime.onValueChanged(Callbacks.java:193)
	at fi.dy.masa.tweakeroo.config.Callbacks$FeatureCallbackSlime.onValueChanged(Callbacks.java:171)
	at fi.dy.masa.malilib.config.options.ConfigBase.onValueChanged(ConfigBase.java:75)
	at fi.dy.masa.malilib.config.options.ConfigBoolean.setBooleanValue(ConfigBoolean.java:47)
	at fi.dy.masa.malilib.config.options.ConfigTypeWrapper.setBooleanValue(ConfigTypeWrapper.java:307)
	at fi.dy.masa.malilib.config.IConfigBoolean.toggleBooleanValue(IConfigBoolean.java:13)
	at fi.dy.masa.malilib.gui.button.ConfigButtonBoolean.onMouseClickedImpl(ConfigButtonBoolean.java:21)
	at fi.dy.masa.malilib.gui.widgets.WidgetBase.onMouseClicked(WidgetBase.java:92)
	at fi.dy.masa.malilib.gui.widgets.WidgetContainer.onMouseClicked(WidgetContainer.java:64)
	at fi.dy.masa.malilib.gui.widgets.WidgetListBase.onMouseClicked(WidgetListBase.java:109)
	at fi.dy.masa.malilib.gui.widgets.WidgetListConfigOptionsBase.onMouseClicked(WidgetListConfigOptionsBase.java:47)
	at fi.dy.masa.malilib.gui.GuiListBase.onMouseClicked(GuiListBase.java:97)
	at fi.dy.masa.malilib.gui.GuiConfigsBase.onMouseClicked(GuiConfigsBase.java:192)
	at fi.dy.masa.malilib.gui.GuiBase.method_25402(GuiBase.java:196)
	at net.minecraft.class_312.method_1611(class_312.java:94)

-- Affected screen --
Details:
	Screen name: fi.dy.masa.tweakeroo.gui.GuiConfigs
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:490)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:101)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:165)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:749)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.17 Pre-release 4
	Minecraft Version ID: 1.17-pre4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 748724480 bytes (714 MiB) / 1174405120 bytes (1120 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 4
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Athlon(tm) X4 950 Quad Core Processor      
	Identifier: AuthenticAMD Family 21 Model 101 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 3,49
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce GTX 1050 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095,00
	Graphics card #0 deviceId: 0x1c82
	Graphics card #0 versionInfo: DriverVersion=27.21.14.6647
	Memory slot #0 capacity (MB): 8192,00
	Memory slot #0 clockSpeed (GHz): 2,40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192,00
	Memory slot #1 clockSpeed (GHz): 2,40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 34649,13
	Virtual memory used (MB): 13540,93
	Swap memory total (MB): 18328,00
	Swap memory used (MB): 51,54
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric: Fabric API 0.34.8+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b4463a0
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.2+a02b4463a0
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+9e521e13a0
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b4463a0
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+a02b4463a0
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afaa0
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b4463a0
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b4463a0
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.4+b7ab6121a0
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.10+a02b4463a0
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b4463a0
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.8+a02b4463a0
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afaa0
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+a02b4463a0
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b4463a0
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab6121a0
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b4463a0
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3ea0
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b4463a0
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b4463a0
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afaa0
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b4463a0
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.11+b7ab6121a0
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b4463a0
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afaa0
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab6121a0
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b4463a0
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b4463a0
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.9+a02b4463a0
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.2+a02b4463a0
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b4463a0
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b4463a0
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b4463a0
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b4463a0
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afaa0
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b4463a0
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab6121a0
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.3+b7ab6121a0
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b4463a0
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.9+75bf7f0fa0
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b4463a0
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b4463a0
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab6121a0
		fabricloader: Fabric Loader 0.11.3
		itemscroller: Item Scroller 0.15.0-dev.20210603.144636
		java: OpenJDK 64-Bit Server VM 16
		litematica: Litematica 0.0.0-dev.20210603.144652
		malilib: MaLiLib 0.10.0+dev.22
		minecraft: Minecraft 1.17-beta.4
		minihud: MiniHUD 0.19.0-dev.20210603.144705
		modmenu: Mod Menu 2.0.0-beta.7
		tweakeroo: Tweakeroo 0.10.0-dev.20210603.144717
	Launched Version: fabric-loader-0.11.3-1.17-pre4
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 466.47, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, Fabric Mods
	Current Language: Deutsch (Deutschland)
	CPU: 4x AMD Athlon(tm) X4 950 Quad Core Processor

**Comment by maruohon** [comment]
Fixed in the latest build
