### ISSUE TITLE
chest preview crashes the game

### ISSUE THREAD

**Issue by KrisCris** [maruohon/tweakeroo#308]
---- Minecraft Crash Report ----
// Why did you do that?

Time: 12/30/21, 4:03 PM
Description: Unexpected error

java.lang.RuntimeException: Mixin transformation of fi.dy.masa.tweakeroo.renderer.RenderUtils failed
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.12)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at fi.dy.masa.tweakeroo.event.RenderHandler.onRenderGameOverlayPost(RenderHandler.java:42)
	at fi.dy.masa.malilib.event.RenderEventHandler.onRenderGameOverlayPost(RenderEventHandler.java:66)
	at net.minecraft.client.gui.hud.InGameHud.handler$dkg000$onGameOverlayPost(InGameHud:5517)
	at net.minecraft.client.gui.hud.InGameHud.render(InGameHud:416)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:856)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1117)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:733)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.client.MinecraftClient.modify$dog000$atTheEndOfSecondCatchBeforePrintingCrashReport(MinecraftClient:18046)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:760)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.client.MinecraftClient.modify$dog000$atTheEndOfSecondCatchBeforePrintingCrashReport(MinecraftClient:18046)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:760)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.client.MinecraftClient.modify$dog000$atTheEndOfSecondCatchBeforePrintingCrashReport(MinecraftClient:18046)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:760)
	at net.minecraft.client.main.Main.main(Main:238)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247)
	... 35 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in fi/dy/masa/tweakeroo/renderer/RenderUtils::renderInventoryOverlay(Lnet/minecraft/class_310;Lnet/minecraft/class_4587;)V has incompatible changes at opcode 125 in callback masa_gadget_mod.mixins.json:tweakeroo.inventoryPreviewSupportShulkerBoxItemEntity.MixinRenderUtils->@Inject::getTraceEntity(Lnet/minecraft/class_310;Lnet/minecraft/class_4587;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/class_1937;Lnet/minecraft/class_1657;Lnet/minecraft/class_239;Lnet/minecraft/class_1263;Lnet/minecraft/class_2480;Lnet/minecraft/class_1309;Lnet/minecraft/class_1297;)V from mod masa_gadget_mod.
 Expected: [Lnet/minecraft/class_1937;, Lnet/minecraft/class_1657;, Lnet/minecraft/class_239;, Lnet/minecraft/class_1263;, Lnet/minecraft/class_2480;, Lnet/minecraft/class_1309;, Lnet/minecraft/class_1297;]
    Found: [Lnet/minecraft/class_1937;, Lnet/minecraft/class_1297;, Lnet/minecraft/class_239;, Lnet/minecraft/class_1263;, Lnet/minecraft/class_2480;, Lnet/minecraft/class_1309;, Lnet/minecraft/class_1297;]
Available: [Lnet/minecraft/class_1937;, Lnet/minecraft/class_1297;, Lnet/minecraft/class_239;, Lnet/minecraft/class_1263;, Lnet/minecraft/class_2480;, Lnet/minecraft/class_1309;, Lnet/minecraft/class_1297;]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:545)
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:495)
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1374)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 38 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at fi.dy.masa.tweakeroo.event.RenderHandler.onRenderGameOverlayPost(RenderHandler.java:42)
	at fi.dy.masa.malilib.event.RenderEventHandler.onRenderGameOverlayPost(RenderEventHandler.java:66)
	at net.minecraft.class_329.handler$dkg000$onGameOverlayPost(class_329.java:5517)
	at net.minecraft.class_329.method_1753(class_329.java:416)

-- Affected level --
Details:
	All players: 1 total; [class_746['connlost'/2877, l='ClientLevel', x=-63.50, y=71.00, z=-6.50]]
	Chunk stats: 4096, 923
	Level dimension: minecraft:overworld
	Level spawn location: World: (-64,67,-16), Section: (at 0,3,0 in -4,4,-1; chunk contains blocks -64,-64,-16 to -49,319,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 233 game time, 233 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:408)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:757)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$dog000$atTheEndOfSecondCatchBeforePrintingCrashReport(class_310.java:18046)
	at net.minecraft.class_310.method_1514(class_310.java:760)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$dog000$atTheEndOfSecondCatchBeforePrintingCrashReport(class_310.java:18046)
	at net.minecraft.class_310.method_1514(class_310.java:760)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$dog000$atTheEndOfSecondCatchBeforePrintingCrashReport(class_310.java:18046)
	at net.minecraft.class_310.method_1514(class_310.java:760)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Last reload --
Details:
	Reload number: 4
	Reload reason: manual
	Finished: Yes
	Packs: Default, Fabric Mods, continuity/default, continuity/glass_pane_culling_fix, lambdabettergrass/default, IslanaArmorAccessories1.0.5, Masa_汉化资源包V2e [1.12-1.17].zip

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 2104926608 bytes (2007 MiB) / 8589934592 bytes (8192 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800H with Radeon Graphics         
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.19
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3060 Laptop GPU
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2560
	Graphics card #0 versionInfo: DriverVersion=30.0.14.9729
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 42671.75
	Virtual memory used (MB): 35990.65
	Swap memory total (MB): 10051.70
	Swap memory used (MB): 801.20
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms8192m -Xmx8192m
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.5.4
		allstackable: All Stackable 1.5.1-1.18.1
		appleskin: AppleSkin mc1.18-2.2.0
		architectury: Architectury 3.1.45
		authme: Auth Me 2.2.0
		betterpingdisplay: Better Ping Display 1.1.1
		betterthirdperson: Better Third Person 1.5.4
		blur: Blur (Fabric) 2.4.1
		bobby: Bobby 3.1.0
		carpet: Carpet Mod 1.4.56
		carpet-extra: Carpet Extra 1.4.56
		carpet-tis-addition: Carpet TIS Addition 1.28.1
		citresewn: CITResewn 0.8.1-1.18
		cleancut: CleanCut 1.18-4.0-fabric
		clientcommands: Client Commands 2.6
		clientcommands-scripting: Clientcommands Scripting 1.3
		cloth-api: Cloth API 2.0.54
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config: Cloth Config v6 6.1.48
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		com_typesafe_config: config 1.4.1
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		confabricate: confabricate 2.1.0-SNAPSHOT+4.1.1
		continuity: Continuity 1.0.3+1.18
		earthtojavamobs: Earth2Java 1.7.4+1.18
		easiervillagertrading: EasierVillagerTrading 1.18-fabric0.43.1-1.5.4
		enhancedblockentities: Enhanced Block Entities 0.5+1.18
		fabric: Fabric API 0.45.0+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cdc8
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.0+17be577f65
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a965
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d95c8
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c665
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73d65
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.7+43d2957165
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378a65
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f1765
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cd65
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d9565
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f365
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cd65
		fabric-language-kotlin: Fabric Language Kotlin 1.6.4+kotlin.1.5.30
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca33565
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d9565
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d9565
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.7+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d9565
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d9565
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.0+3b82842e65
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.8+3ac43d9565
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1ac65
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.8.6+533be9ba65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.9+3ac43d9565
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.12+3ac43d9565
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d765
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378a65
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d9514
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d9565
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d9565
		fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a765
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d9565
		fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.4+7de09f5565
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.6+b4f4f6cd65
		fabricloader: Fabric Loader 0.12.12
		fabrishot: Fabrishot 1.6.0
		fallingleaves: Falling Leaves 1.8.1+1.18.1
		fallingtree: FallingTree 3.0.0
		firstperson: FirstpersonModel 2.1.0
		gbfabrictools: GBfabrictools 1.3.4+1.18
		ias: In-Game Account Switcher 7.1.3
		imblocker: IMBlockerFabric 1.0.17
		indium: Indium 1.0.2-alpha1+mc1.18
		inspecio: Inspecio 1.1.0+1.17
		inventoryprofilesnext: Inventory Profiles Next 1.2.2
		io_leangen_geantyref_geantyref: geantyref 1.3.11
		iris: Iris 1.1.3
		itemscroller: Item Scroller 0.15.0
		java: Java HotSpot(TM) 64-Bit Server VM 17
		kirin: Kirin UI 1.10.0-beta.2
		krypton: Krypton 0.1.6
		lambdabettergrass: LambdaBetterGrass 1.2.2+1.17
		language-loader-fix: Language-Loader-Fix 1.1.1+build.3
		lazydfu: LazyDFU 0.1.2
		libzoomer: LibZoomer 0.3.0+1.17.1
		litematica: Litematica 0.9.0
		lithium: Lithium 0.7.6
		magiclib: MagicLib 1.0.0+build.undefined
		malilib: MaLiLib 0.10.0-dev.26
		masa_gadget_mod: Masa Gadget 21w41a-2.0.6
		midnightlib: MidnightLib 0.3.1
		minecraft: Minecraft 1.18.1
		minihud: MiniHUD 0.19.0-dev.20211114.132606
		minihud-injector: MiniHUD-Injector 1.2.0+build.3
		modmanager: Mod Manager 1.2.1+1.18
		modmenu: Mod Menu 3.0.1
		multiconnect-api: MultiConnect API 1.5
		notenoughanimations: NotEnoughAnimations 1.4.0
		notenoughcrashes: Not Enough Crashes 4.1.3+1.18.1
		okzoomer: Ok Zoomer 5.0.0-beta.3+1.17.1
		ommc: Oh My Minecraft Client 21w40a-0.3.9
		orderly: Orderly 2.0.1-alpha.2+custom-1.18
		org_anarres_jcpp: jcpp 1.4.14
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.30
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.2
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.2
		org_joml_joml: joml 1.10.2
		org_quiltmc_quilt-json5: quilt-json5 1.0.0
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		org_spongepowered_configurate-core: configurate-core 4.1.1
		org_spongepowered_configurate-extra-dfu4: configurate-extra-dfu4 4.1.1
		org_spongepowered_configurate-gson: configurate-gson 4.1.1
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.1
		org_yaml_snakeyaml: snakeyaml 1.29
		paperdoll: PaperDoll 1.0.0-mc1.18-pre1
		pca: Plusls carpet addition mod 0.2.3
		phosphor: Phosphor 0.8.1
		presencefootsteps: Presence Footsteps 1.4.0
		roughlyenoughitems: Roughly Enough Items 7.1.357
		satin: Satin 1.7.0
		skinlayers: 3d Skin Layers 1.3.1
		sodium: Sodium 0.4.0-alpha5+build.9
		sodium-extra: Sodium Extra 0.3.7
		spruceui: SpruceUI 3.3.2+1.17
		totemplus: Totem Plus 1.2-1.18.1
		tweakeroo: Tweakeroo 0.11.0
		tweakmyclient: TweakMyClient 1.1.11+bba69f9
		waveycapes: WaveyCapes 1.0.4
		whereisit: Where Is It 1.14.4
		worldedit: WorldEdit 7.2.9-SNAPSHOT+6045-3fa364b
		wthit: wthit 4.4.0
		xaerobetterpvp: Better PVP Mod 21.23.0
		xaeroworldmap: Xaero's World Map 1.19.0
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2 GL version 3.2.0 NVIDIA 497.29, NVIDIA Corporation
	Window size: 2560x1351
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Polygon modes for <face> are disabled in the current profile.' x 6
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, continuity/default, continuity/glass_pane_culling_fix, lambdabettergrass/default (incompatible), file/IslanaArmorAccessories1.0.5 (incompatible), file/Masa_汉化资源包V2e [1.12-1.17].zip (incompatible)
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 5800H with Radeon Graphics 
	Server Running: true
	Player Count: 1 / 8; [class_3222['connlost'/2877, l='ServerLevel[New World]', x=-63.50, y=71.00, z=-6.50]]
	Data Packs: vanilla, Fabric Mods
	Client Crashes Since Restart: 4
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), Tweakeroo (tweakeroo), Not Enough Crashes (notenoughcrashes), MaLiLib (malilib)

**Comment by maruohon** [comment]
That's caused by an old or incompatible MasaGadget mod version failing to modify some Tweakeroo code.

**Comment by KrisCris** [comment]
Thanks for the info! This is fixed in masaGadget's latest build :)
