### ISSUE TITLE
Conflict Found

### ISSUE THREAD

**Issue by NopeProsOnly** [maruohon/tweakeroo#380]
https://modrinth.com/mod/canimation

This is a conflict...

**Comment by maruohon** [comment]
ok

**Comment by vacla** [comment]
@kaden-tech Can you sent a crashlog since that will make it much easier to fix it.

**Comment by NopeProsOnly** [comment]
Sure just gimme a few moments.

I'm having some technical difficulties.

**Comment by NopeProsOnly** [comment]
[crash-2022-10-27_10.52.09-client.txt](https://github.com/maruohon/tweakeroo/files/9883779/crash-2022-10-27_10.52.09-client.txt)

**Comment by maruohon** [comment]
That crash is due to some kind of infinite recursion between ReplayMod and some FreeCam mod.

**Comment by NopeProsOnly** [comment]
What part of tweakeroo uses the chat stuff? Why is it doing a loop?

**Comment by vacla** [comment]
@kaden-tech there is no reference here to tweakeroo

**Comment by NopeProsOnly** [comment]
The conflict is with tweakeroo... can you just stop the loop?

**Comment by vacla** [comment]
From what I see says here:
`at com.replaymod.replay.camera.CameraEntity.method_6115(CameraEntity.java:555)
	at net.xolt.freecam.util.FreeCamera.method_6115(FreeCamera.java:72)
	at com.replaymod.replay.camera.CameraEntity.method_6115(CameraEntity.java:555)
	at net.xolt.freecam.util.FreeCamera.method_6115(FreeCamera.java:72)
	at com.replaymod.replay.camera.CameraEntity.method_6115(CameraEntity.java:555)
	at net.xolt.freecam.util.FreeCamera.method_6115(FreeCamera.java:72)
	at com.replaymod.replay.camera.CameraEntity.method_6115(CameraEntity.java:555)
	at net.xolt.freecam.util.FreeCamera.method_6115(FreeCamera.java:72)`
	
That it is `replaymod: Replay Mod 1.19.1-2.6.8` and `freecam: Freecam 1.1.5`

**Comment by NopeProsOnly** [comment]
Then I gave the wrong log...

**Comment by NopeProsOnly** [comment]
Just a sec

**Comment by NopeProsOnly** [comment]
[latest.log](https://github.com/maruohon/tweakeroo/files/9888783/latest.log)

**Comment by ErrorNoInternet** [comment]
Also seems to be happening to me
