### ISSUE TITLE
writeMaps caused the game to exit

### ISSUE THREAD

**Issue by ALiaoHaolong** [maruohon/tweakeroo#517]
this tool worked well in 1.20.4, but cannot work in 1.21. I already disabled others mod and resources. here is my crash-reports.
english isnt my mother language. i am sorry for some confused descriptions.
```text
---- Minecraft Crash Report ----
// There are four lights!

Time: 2024-08-22 00:12:32
Description: Unexpected error

java.lang.ClassCastException: class net.minecraft.class_9209 cannot be cast to class java.lang.String (net.minecraft.class_9209 is in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @598067a5; java.lang.String is in module java.base of loader 'bootstrap')
	at fi.dy.masa.tweakeroo.util.MiscUtils.writeAllMapsAsImages(MiscUtils.java:496)
	at fi.dy.masa.tweakeroo.config.Callbacks.lambda$init$6(Callbacks.java:96)
	at fi.dy.masa.malilib.hotkeys.KeybindMulti.triggerKeyAction(KeybindMulti.java:185)
	at fi.dy.masa.malilib.hotkeys.KeybindMulti.updateIsPressed(KeybindMulti.java:145)
	at fi.dy.masa.malilib.event.InputEventHandler.checkKeyBindsForChanges(InputEventHandler.java:276)
	at fi.dy.masa.malilib.event.InputEventHandler.onKeyInput(InputEventHandler.java:147)
	at net.minecraft.class_309.handler$znk000$malilib$onKeyboardInput(class_309.java:1121)
	at net.minecraft.class_309.method_1466(class_309.java:346)
	at net.minecraft.class_309.method_22678(class_309.java:499)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_309.method_22676(class_309.java:499)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:161)
	at net.minecraft.class_1041.method_15998(class_1041.java:303)
	at net.minecraft.class_310.method_1523(class_310.java:1307)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at fi.dy.masa.tweakeroo.util.MiscUtils.writeAllMapsAsImages(MiscUtils.java:496)
	at fi.dy.masa.tweakeroo.config.Callbacks.lambda$init$6(Callbacks.java:96)
	at fi.dy.masa.malilib.hotkeys.KeybindMulti.triggerKeyAction(KeybindMulti.java:185)
	at fi.dy.masa.malilib.hotkeys.KeybindMulti.updateIsPressed(KeybindMulti.java:145)
	at fi.dy.masa.malilib.event.InputEventHandler.checkKeyBindsForChanges(InputEventHandler.java:276)
	at fi.dy.masa.malilib.event.InputEventHandler.onKeyInput(InputEventHandler.java:147)
	at net.minecraft.class_309.handler$znk000$malilib$onKeyboardInput(class_309.java:1121)
	at net.minecraft.class_309.method_1466(class_309.java:346)
	at net.minecraft.class_309.method_22678(class_309.java:499)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_309.method_22676(class_309.java:499)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:161)

-- Uptime --
Details:
	JVM uptime: 53.539s
	Wall uptime: 41.176s
	High-res time: 39.925s
	Client ticks: 734 ticks / 36.700s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2501)
	at net.minecraft.class_310.method_54580(class_310.java:949)
	at net.minecraft.class_310.method_1514(class_310.java:905)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)

-- Affected level --
Details:
	All players: 1 total; [class_746['An_Night'/8085086, l='ClientLevel', x=1541.91, y=78.00, z=-529.60]]
	Chunk stats: 289, 145
	Level dimension: minecraft:overworld
	Level spawn location: World: (1666,108,-933), Section: (at 2,12,11 in 104,6,-59; chunk contains blocks 1664,-64,-944 to 1679,319,-929), Region: (3,-2; contains chunks 96,-64 to 127,-33, blocks 1536,-64,-1024 to 2047,319,-513)
	Level time: 1684378914 game time, 1707228751 day time
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.21-R0.1-SNAPSHOT:8b195d1:1852) <- Purpur
	Server type: Non-integrated multiplayer server
	Tracked entity count: 286

-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: Yes
	Packs: vanilla, fabric, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, malilib, tweakeroo

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.4, Amazon.com Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Amazon.com Inc.
	Memory: 152027008 bytes (144 MiB) / 784334848 bytes (748 MiB) up to 5045747712 bytes (4812 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1660 SUPER
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 6144.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.15.6081
	Memory slot #0 capacity (MiB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.00
	Memory slot #0 type: DDR4
	Virtual memory max (MiB): 23978.62
	Virtual memory used (MiB): 14667.36
	Swap memory total (MiB): 7680.00
	Swap memory used (MiB): 245.92
	Space in storage for jna.tmpdir (MiB): available: 376291.75, total: 624536.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 376291.75, total: 624536.00
	Space in storage for io.netty.native.workdir (MiB): available: 376291.75, total: 624536.00
	Space in storage for java.io.tmpdir (MiB): available: 31186.54, total: 228234.06
	Space in storage for workdir (MiB): available: 376291.75, total: 624536.00
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn721m -Xmx4812m
	Fabric Mods: 
		fabric-api: Fabric API 0.102.0+1.21
			fabric-api-base: Fabric API Base 0.4.42+6573ed8cd1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.68+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bcd1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a7d1
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366fd1
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd9d1
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.16+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.19+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.5.0+c5e2b5c6d1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.27+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.16+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.12+ba9dae06d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd9d1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.4+78017270d1
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a7d1
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b3d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.12+6c1df360d1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.14+3f89f5a5d1
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.2+3f89f5a5d1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6bd1
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.2+60c3209bd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.0+a551f7a4d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.12+65089712d1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.2+60c3209bd1
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49cd1
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49cd1
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b3d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b3d1
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd0d1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b1d1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.0+56599129d1
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b5597344d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.86+b5597344d1
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8cd1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.16+3dccd343d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+176f9036d1
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		java: OpenJDK 64-Bit Server VM 21
		malilib: MaLiLib 0.21.0
		minecraft: Minecraft 1.21
		tweakeroo: Tweakeroo 0.20.999-sakura.19
	Launched Version: 1.21-Fabric 0.15.11
	Launcher name: PCL
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2 GL version 3.2.0 NVIDIA 560.81, NVIDIA Corporation
	Window size: 2560x1361
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Render Distance: 5/16 chunks
	Resource Packs: vanilla, fabric, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, malilib, tweakeroo (incompatible)
	Current Language: zh_cn
	Locale: zh_CN
	System encoding: GBK
	File encoding: UTF-8
	CPU: 8x Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz
```

**Comment by sakura-ryoko** [comment]
I found the problem, and will have it fixed under the next -sakura release for 1.21
