### ISSUE TITLE
OptiFabric compatibility

### ISSUE THREAD

**Issue by vkorn** [maruohon/tweakeroo#6]
Hey, first of all thanks a lot for all the hard work on this awesome mod. 

I'm trying a new [OptiFabric](https://github.com/modmuss50/OptiFabric) mod with 1.14.2 and unfortunately it seems that it has some conflicts with tweakeroo. I'm not quite sure what is the best place to address it tho, since OptiFabric does some remapping internally. Seems that this is related to a key mappings bindings, but for example your other mod MiniHud, works just fine. 

```
Mixin apply failed mixins.tweakeroo.json:MixinMinecraftClient -> net.minecraft.class_310: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Resolution error: unable to find corresponding type for fi/dy/masa/tweakeroo/mixin/IMixinKeyBinding in hierarchy of net/minecraft/class_310 org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Resolution error: unable to find corresponding type for fi/dy/masa/tweakeroo/mixin/IMixinKeyBinding in hierarchy of net/minecraft/class_310 at org.spongepowered.asm.mixin.transformer.MixinTargetContext.findRealType(MixinTargetContext.java:438) at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformSingleDescriptor(MixinTargetContext.java:913) at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformDescriptor(MixinTargetContext.java:865) at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformTypeNode(MixinTargetContext.java:654) at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:471) at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyNormalMethod(MixinApplicatorStandard.java:446) at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMethods(MixinApplicatorStandard.java:433) at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:313) at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:281) at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353) at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724) at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703) at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509) at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:179) at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:142) at java.lang.ClassLoader.loadClass(ClassLoader.java:357) at net.minecraft.client.main.Main.main(Main.java:154) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170) at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129) at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
```

**Comment by vkorn** [comment]
Thank you! works like a charm with the latest version.
