### ISSUE TITLE
Fabric crash on start

### ISSUE THREAD

**Issue by ProkopRandacek** [maruohon/tweakeroo#7]
The game crashes on start :D

fabric-loader-0.4.8+build.155-1.14.2
tweakeroo-fabric-1.14.2-0.9.6

[0624/145926:INFO:GameCallbacks.cpp(198)] launcher/launcher (main) info 
Exception in thread "main" java.lang.RuntimeException: Failed to resolve mods!
at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:147)
at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:120)
at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: net.fabricmc.loader.discovery.ModResolutionException: Unsatisfied dependencies!
Mod tweakeroo depends on mod {fabric-events-lifecycle-v0 @ [*]}, which is missing!
at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:297)
at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:483)
at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:145)
... 2 more

**Comment by maruohon** [comment]
For Tweakeroo 0.9.x you need malilib 0.9.6 and the Fabric API.
https://minecraft.curseforge.com/projects/malilib/files/2716497
https://minecraft.curseforge.com/projects/fabric/files/2720368

**Comment by ProkopRandacek** [comment]
Oh sorry, my bad.
